# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 02:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170602_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_apps',
            name='callback_uri',
            field=models.URLField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='api_apps',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='api_apps',
            name='website',
            field=models.URLField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='api_heartbeat',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
